#!/bin/sh
#
# Created: 2019 --- -- --:--:--
# Updated: 2020 Feb 09 22:38:20  
#
# Requirements:
#   - jq
#   - curl
# If there are any stdin then don't open fzf interactively instead use -f 
# option to print the result.

url='https://sozluk.gov.tr/autocomplete.json'
cachedir=$HOME/.cache/sozlukgovtr
cache=$cachedir/autocomplete
data=/tmp/turkish_autocomplete.json
mkdir -p $cachedir

if ! [ -s $cache ]; then
	if ! [ -s $data ]; then
		curl -so $data $url || exit 2;
	fi
	cat $data | jq -r '.[].madde' > $cache;
fi && cat $cache | fzf;

# Also check this
#
# curl 'https://sozluk.gov.tr/yazim?ara=merhaba' \
# -H 'Accept: application/json' \
