#!/bin/sh

# =========================================================================== #
# File:        imla                                                           #
# Description: search all the words through thesaurus of sozluk.gov.tr        #
# Author:      ihsan <ihsanl at pm dot me>                                    #
# License:     MIT License                                                    #
#                                                                             #
# # TODO 1586564643: curl 'https://sozluk.gov.tr/yazim?ara=merhaba' \         #
# -H 'Accept: application/json' \                                             #
# =========================================================================== #

cat /usr/share/dict/turkish-words | fzf
