#!/bin/sh

# =========================================================================== #
# File:        sozlukgovtr                                                    #
# Description: get meaning of a phrase from https://sozluk.gov.tr             #
# Author:      ihsan <ihsanl at pm dot me>                                    #
# Updated At:  1586565423                                                     #
# License:     MIT License                                                    #
# Requirements: jq, curl                                                      #
# =========================================================================== #

URL='https://sozluk.gov.tr/gts'
CACHEDIR=/usr/share/sozlukgovtr/

( [ $# -gt 0 ] && echo $@ || cat /dev/stdin ) | while read args; do 
	CACHE=$CACHEDIR/`echo $args | tr ' ' '+'`.json
	[ -f $CACHE ] || curl -G --data-urlencode "ara=$args" -so $CACHE $URL &&
	cat $CACHE | jq -r '.[].anlamlarListe[].anlam' 2> /dev/null;
done
